CREATE DATABASE QLBongDa
GO
USE QLBongDa
GO

CREATE TABLE CAUTHU (
    MACT NUMERIC(10,0) IDENTITY(1,1) PRIMARY KEY, /* bắt đầu đếm từ 1, tăng 1 mỗi lần đếm */
    HOTEN NVARCHAR(100) NOT NULL,
    VITRI NVARCHAR(20) NOT NULL,
    NGAYSINH DATETIME ,
    DIACHI NVARCHAR(200) NULL,
    MACLB VARCHAR(5) NOT NULL,
    MAQG VARCHAR(5) NOT NULL,
    SO INT NOT NULL
); 
GO

--  Bảng QUOCGIA
CREATE TABLE QUOCGIA (
    MAQG VARCHAR(5) PRIMARY KEY,
    TENQG NVARCHAR(60) NOT NULL
); 
GO

-- Bảng TINH
CREATE TABLE TINH (
    MATINH VARCHAR(5) PRIMARY KEY,
    TENTINH NVARCHAR(100) NOT NULL
); 
GO

-- Bảng SANVD
CREATE TABLE SANVD (
    MASAN VARCHAR(5) PRIMARY KEY,
    TENSAN NVARCHAR(100) NOT NULL,
    DIACHI NVARCHAR(200)
); 
GO

--  Bảng CAULACBO
CREATE TABLE CAULACBO (
    MACLB VARCHAR(5) PRIMARY KEY,
    TENCLB NVARCHAR(100) NOT NULL,
    MASAN VARCHAR(5) NOT NULL,
    MATINH VARCHAR(5) NOT NULL
); 
GO

-- Bảng HUANLUYENVIEN
CREATE TABLE HUANLUYENVIEN (
    MAHLV VARCHAR(5) PRIMARY KEY,
    TENHLV NVARCHAR(100) NOT NULL,
    NGAYSINH DATETIME,
    DIACHI NVARCHAR(200),
    DIENTHOAI NVARCHAR(20),
    MAQG VARCHAR(5) NOT NULL
); 
GO

-- bảng HLV_CLB
CREATE TABLE HLV_CLB
(
    MAHLV VARCHAR(5),
    MACLB VARCHAR(5),
    VAITRO NVARCHAR(100) NOT NULL,
	PRIMARY KEY(MAHLV, MACLB),
); 
GO

-- bảng TRANDAU
CREATE TABLE TRANDAU
(
    MATRAN NUMERIC(10,0) IDENTITY(1,1) PRIMARY KEY,
    NAM INT NOT NULL,
    VONG INT NOT NULL,
    NGAYTD DATETIME NOT NULL,
    MACLB1 VARCHAR(5) NOT NULL,
    MACLB2 VARCHAR(5) NOT NULL,
    MASAN VARCHAR(5) NOT NULL,
    KETQUA VARCHAR(5) NOT NULL
); 
GO

-- bảng BXH
CREATE TABLE BANGXH
(
    MACLB VARCHAR(5),
    NAM INT,
    VONG INT,
    SOTRAN INT NOT NULL,
    THANG INT NOT NULL,
    HOA INT NOT NULL,
    THUA INT NOT NULL,
    HIEUSO VARCHAR(5) NOT NULL,
    DIEM INT NOT NULL,
    HANG INT NOT NULL,
	PRIMARY KEY(MACLB,NAM,VONG),
);
GO

-- CAULACBO → SANVD
ALTER TABLE CAULACBO
ADD CONSTRAINT FK_CLB_SAN
FOREIGN KEY (MASAN)
REFERENCES SANVD(MASAN); 
GO

-- CAULACBO → TINH
ALTER TABLE CAULACBO
ADD CONSTRAINT FK_CLB_TINH
FOREIGN KEY (MATINH)
REFERENCES TINH(MATINH); 
GO

-- HUANLUYENVIEN → QUOCGIA
ALTER TABLE HUANLUYENVIEN
ADD CONSTRAINT FK_HLV_QG
FOREIGN KEY (MAQG)
REFERENCES QUOCGIA(MAQG); 
GO

-- HLV -> mã HLV
ALTER TABLE HLV_CLB
ADD CONSTRAINT FK_HLV_CLB_HLV
FOREIGN KEY (MAHLV)
REFERENCES HUANLUYENVIEN(MAHLV); 
GO

-- CLB -> mã CLB
ALTER TABLE HLV_CLB
ADD CONSTRAINT FK_HLV_CLB_CLB
FOREIGN KEY (MACLB)
REFERENCES CAULACBO(MACLB); 
GO

-- khóa ngoại bảng TRANDAU
-- CLB 1
ALTER TABLE TRANDAU
ADD CONSTRAINT FK_TRANDAU_CLB1
FOREIGN KEY (MACLB1)
REFERENCES CAULACBO(MACLB);

-- CLB2
ALTER TABLE TRANDAU
ADD CONSTRAINT FK_TRANDAU_CLB2
FOREIGN KEY (MACLB2)
REFERENCES CAULACBO(MACLB);

-- SAN
ALTER TABLE TRANDAU
ADD CONSTRAINT FK_TRANDAU_SAN
FOREIGN KEY (MASAN)
REFERENCES SANVD(MASAN);

-- khóa ngoại bảng BXH
ALTER TABLE BANGXH
ADD CONSTRAINT FK_BANGXH_CLB
FOREIGN KEY (MACLB)
REFERENCES CAULACBO(MACLB);

DROP LOGIN [LAPTOP-TNT2JUJI\ACER];

CREATE LOGIN [Alterix\ACER] FROM WINDOWS;
ALTER SERVER ROLE sysadmin ADD MEMBER [Alterix\ACER];